// AUTO-GENERATED by scripts/sync_config.py
// Do not edit this file directly. Edit project.config.json instead.

window.APP_CONFIG = {
  aws: {
    region: "ap-south-1",
    s3Bucket: "doc-parser-app-as",
    cognito: {
      userPoolId: "ap-south-1_72jrSgVgi",
      clientId: "73o39h36c36r253ijh5sstnj7e",
      identityPoolId: "ap-south-1:572e2fdb-95bc-4675-ba7d-aec010896169",
      hostedUiDomain: "https://ap-south-172jrsgvgi.auth.ap-south-1.amazoncognito.com",
      redirectUri: "https://doc-parser-app-as.s3.ap-south-1.amazonaws.com/doc-parser.html",
    },
  },
  api: {
    processUrl: "https://11ghprcjk7.execute-api.ap-south-1.amazonaws.com/process",
  },
};
