import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
EXAMPLE_CONFIG_PATH = ROOT / "project.config.example.json"
CONFIG_PATH = ROOT / "project.config.json"

def prompt(message: str, default: str = "") -> str:
    prompt_msg = f"{message} [{default}]: " if default else f"{message}: "
    value = input(prompt_msg).strip()
    return value if value else str(default)

def sync_files(cfg: dict):
    # Extract
    region = cfg.get("aws", {}).get("region", "")
    bucket = cfg.get("aws", {}).get("s3Bucket", "")
    cognito = cfg.get("aws", {}).get("cognito", {})
    user_pool_id = cognito.get("userPoolId", "")
    client_id = cognito.get("clientId", "")
    identity_pool_id = cognito.get("identityPoolId", "")
    process_url = cfg.get("api", {}).get("processUrl", "")

    # Write JS
    web_config_path = ROOT / "web-app" / "src" / "config.js"
    web_config_path.write_text(
        "\n".join([
            "// AUTO-GENERATED by setup.py",
            "// Do not edit this file directly. Edit project.config.json instead.",
            "",
            "const APP_CONFIG = {",
            "  aws: {",
            f'    region: {json.dumps(region)},',
            f'    s3Bucket: {json.dumps(bucket)},',
            "    cognito: {",
            f'      userPoolId: {json.dumps(user_pool_id)},',
            f'      clientId: {json.dumps(client_id)},',
            f'      identityPoolId: {json.dumps(identity_pool_id)},',
            "    },",
            "  },",
            "  api: {",
            f'    processUrl: {json.dumps(process_url)},',
            "  },",
            "};",
            "",
            "export default APP_CONFIG;",
            ""
        ]), encoding="utf-8"
    )

    # Write Dart
    mobile_config_path = ROOT / "mobile-app" / "lib" / "app_config.dart"
    mobile_config_path.write_text(
        "\n".join([
            "/// AUTO-GENERATED by setup.py",
            "/// Do not edit this file directly. Edit project.config.json instead.",
            "class AppConfig {",
            f"  static const awsRegion = {json.dumps(region)};",
            f"  static const s3BucketName = {json.dumps(bucket)};",
            f"  static const cognitoUserPoolId = {json.dumps(user_pool_id)};",
            f"  static const cognitoClientId = {json.dumps(client_id)};",
            f"  static const cognitoIdentityPoolId = {json.dumps(identity_pool_id)};",
            f"  static const apiProcessUrl = {json.dumps(process_url)};",
            "}",
            ""
        ]), encoding="utf-8"
    )

    print("\n✅ Successfully generated:")
    print(f"  - {web_config_path.relative_to(ROOT)}")
    print(f"  - {mobile_config_path.relative_to(ROOT)}")

def main():
    print("=============================================")
    print("Legal Doc Drafter — Setup")
    print("=============================================\n")

    # Load existing or example config
    from typing import Any, Dict
    cfg: Dict[str, Any] = {"aws": {"cognito": {}}, "api": {}, "backend": {"lambdaEnv": {}}}
    if CONFIG_PATH.exists():
        cfg = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    elif EXAMPLE_CONFIG_PATH.exists():
        cfg = json.loads(EXAMPLE_CONFIG_PATH.read_text(encoding="utf-8"))

    # Ask mode
    mode = input("Do you want to enter AWS details interactively now? (y/n) [y]: ").strip().lower()
    if mode == 'n':
        if not CONFIG_PATH.exists():
            print(f"\nCreating {CONFIG_PATH.relative_to(ROOT)} from example...")
            CONFIG_PATH.write_text(json.dumps(cfg, indent=2), encoding="utf-8")
            print("Please edit it manually, then run this script again to sync.")
            sys.exit(0)
        else:
            print("\nSyncing existing project.config.json to web and mobile apps...")
            sync_files(cfg)
            sys.exit(0)

    # Interactive mode
    aws_region = prompt("AWS Region", cfg.get("aws", {}).get("region", "ap-south-1"))
    s3_bucket = prompt("S3 Bucket Name", cfg.get("aws", {}).get("s3Bucket", ""))
    
    cognito = cfg.get("aws", {}).get("cognito", {})
    user_pool_id = prompt("Cognito User Pool ID", cognito.get("userPoolId", ""))
    client_id = prompt("Cognito App Client ID", cognito.get("clientId", ""))
    identity_pool_id = prompt("Cognito Identity Pool ID", cognito.get("identityPoolId", ""))
    
    process_url = prompt("API Gateway Process URL", cfg.get("api", {}).get("processUrl", ""))

    # Ensure nested dictionaries exist before assigning
    if "aws" not in cfg:
        cfg["aws"] = {}
    if "cognito" not in cfg["aws"]:
        cfg["aws"]["cognito"] = {}
    if "api" not in cfg:
        cfg["api"] = {}
    if "backend" not in cfg:
        cfg["backend"] = {}
    if "lambdaEnv" not in cfg["backend"]:
        cfg["backend"]["lambdaEnv"] = {}

    # Update config
    cfg["aws"]["region"] = aws_region
    cfg["aws"]["s3Bucket"] = s3_bucket
    cfg["aws"]["cognito"]["userPoolId"] = user_pool_id
    cfg["aws"]["cognito"]["clientId"] = client_id
    cfg["aws"]["cognito"]["identityPoolId"] = identity_pool_id
    cfg["api"]["processUrl"] = process_url
    cfg["backend"]["lambdaEnv"]["BUCKET_NAME"] = s3_bucket

    # Save and sync
    CONFIG_PATH.write_text(json.dumps(cfg, indent=2), encoding="utf-8")
    print(f"\nSaved {CONFIG_PATH.relative_to(ROOT)}")
    sync_files(cfg)
    print("\n🎉 Setup Complete! You can now run `npm run dev` or build the Flutter app.")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nSetup cancelled.")
