import json
import pathlib


ROOT = pathlib.Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "project.config.json"


def _require(d: dict, path: str):
    cur = d
    for part in path.split("."):
        if part not in cur:
            raise KeyError(f"Missing config key: {path}")
        cur = cur[part]
    return cur


def main() -> None:
    if not CONFIG_PATH.exists():
        raise SystemExit(
            "Missing project.config.json.\n"
            "Copy project.config.example.json to project.config.json and edit it."
        )

    cfg = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))

    region = _require(cfg, "aws.region")
    bucket = _require(cfg, "aws.s3Bucket")
    user_pool_id = _require(cfg, "aws.cognito.userPoolId")
    client_id = _require(cfg, "aws.cognito.clientId")
    identity_pool_id = _require(cfg, "aws.cognito.identityPoolId")
    hosted_ui_domain = _require(cfg, "aws.cognito.hostedUiDomain")
    redirect_uri = _require(cfg, "aws.cognito.redirectUri")
    process_url = _require(cfg, "api.processUrl")

    # --- Generate web-app/src/config.js ---
    web_config_path = ROOT / "web-app" / "src" / "config.js"
    web_config_path.write_text(
        "\n".join(
            [
                "// AUTO-GENERATED by scripts/sync_config.py",
                "// Do not edit this file directly. Edit project.config.json instead.",
                "",
                "const APP_CONFIG = {",
                "  aws: {",
                f'    region: {json.dumps(region)},',
                f'    s3Bucket: {json.dumps(bucket)},',
                "    cognito: {",
                f'      userPoolId: {json.dumps(user_pool_id)},',
                f'      clientId: {json.dumps(client_id)},',
                f'      identityPoolId: {json.dumps(identity_pool_id)},',
                "    },",
                "  },",
                "  api: {",
                f'    processUrl: {json.dumps(process_url)},',
                "  },",
                "};",
                "",
                "export default APP_CONFIG;",
                "",
            ]
        ),
        encoding="utf-8",
    )

    # --- Generate mobile-app/lib/app_config.dart ---
    mobile_config_path = ROOT / "mobile-app" / "lib" / "app_config.dart"
    mobile_config_path.write_text(
        "\n".join(
            [
                "/// AUTO-GENERATED by scripts/sync_config.py",
                "/// Do not edit this file directly. Edit project.config.json instead.",
                "class AppConfig {",
                f"  static const awsRegion = {json.dumps(region)};",
                f"  static const s3BucketName = {json.dumps(bucket)};",
                f"  static const cognitoUserPoolId = {json.dumps(user_pool_id)};",
                f"  static const cognitoClientId = {json.dumps(client_id)};",
                f"  static const cognitoIdentityPoolId = {json.dumps(identity_pool_id)};",
                f"  static const apiProcessUrl = {json.dumps(process_url)};",
                "}",
                "",
            ]
        ),
        encoding="utf-8",
    )

    print("Updated:")
    print(f"- {web_config_path.relative_to(ROOT)}")
    print(f"- {mobile_config_path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()

