/// AUTO-GENERATED by scripts/sync_config.py
/// Do not edit this file directly. Edit project.config.json instead.
class AppConfig {
  static const awsRegion = "ap-south-1";
  static const s3BucketName = "doc-parser-app-as";
  static const cognitoUserPoolId = "ap-south-1_72jrSgVgi";
  static const cognitoClientId = "73o39h36c36r253ijh5sstnj7e";
  static const cognitoIdentityPoolId = "ap-south-1:572e2fdb-95bc-4675-ba7d-aec010896169";
  static const apiProcessUrl = "https://11ghprcjk7.execute-api.ap-south-1.amazonaws.com/process";
}
